### PR TITLE
Fix to descriptor import

### PR DESCRIPTION
**Pull request by sei-aderr**
Addresses #403 

- Looks like almost all the functionality still works

@GALewis Please review the imports and check if things work as expected or if there are any mappings you want to adjust. For example, I noticed that when we import development environment, we populate the output specification but not the input specification. Let me know if that is working as expected along with all others.

Attached one of each descriptor to aid in testing

[Test - Development Environment.json](https://github.com/user-attachments/files/16432890/Test.-.Development.Environment.json)
[Test - Production Environment.json](https://github.com/user-attachments/files/16432892/Test.-.Production.Environment.json)
[Test - Raw Data.json](https://github.com/user-attachments/files/16432893/Test.-.Raw.Data.json)
[Test - System Context.json](https://github.com/user-attachments/files/16432894/Test.-.System.Context.1.json)

### CODE REVIEW

**Comment by GALewis** [comment]
I found a couple of issues:

System Context
- When importing goals, it leaves Goal 1 blank and starts at Goal 2
- ML Problem type is not being imported

Raw Data
- Same problem as above: data is imported as Dataset 2 and the first one is left blank
- Dataset description is not being imported
- Label should be imported as Label Name
- Data Schema should be imported from Schema

Development Environment
- Not sure why I noticed this just now, but both Input Specification and Output Specification should be "arrays" in the Negotiation Card where each element comes from Input Spec and Output Spec

Production Environment
- All good!

**Comment by sei-aderr** [comment]
@GALewis 

For both goals and datasets, the first is left blank because the import will always add new goals/datasets onto the end of the list to not overwrite any data entered by the user. I can try and add a check to see if there is just one empty goal/dataset in which case it could overwrite, or I can leave it as is.

What are you looking for in raw data > data schema? I see the schema field from raw data properly populating dataset > data schema.

**Comment by sei-aderr** [comment]
@sebastian-echeverria , Grace is looking to adjust the `model.production.input` and `model.production.output` fields to be more similar to the data fields and to store more of the descriptor data on import.

@GALewis Please confirm this is the format that you are expecting.

This would be the new format for the model section of a negotiation card,
```json
  model: {
    development: {
      resources: {
        gpu: "0",
        cpu: "0",
        memory: "0",
        storage: "0",
      },
    },
    production: {
      deployment_platform: "",
      capability_deployment_mechanism: "",
      interface: {
        input: [
          {
            name: "",
            input_spec: [
              {
                name: "",
                description: "",
                type: "",
                expected_values: "",
              },
            ],
          },
        ],
        output: [
          {
            name: "",
            output_spec: [
              {
                name: "",
                description: "",
                type: "",
                expected_values: "",
              },
            ],
          },
        ],
      },
      resources: {
        gpu: "0",
        cpu: "0",
        memory: "0",
        storage: "0",
      },
    },
  },
```

**Comment by GALewis** [comment]
Yes

**Comment by sebastian-echeverria** [comment]
Ok, I can do that. I'll create a new ticket to handle that.

**Comment by sebastian-echeverria** [comment]
#453 and #454 for the I/O array changes.

**Comment by sei-aderr** [comment]
@GALewis 

Based on these changes to the please review the current helper text on each field and determine how those map to the new ones along with any desired helper text for the newly added fields

**Comment by sei-aderr** [comment]
Also please specify the names for fields to display in the frontend. The whole section was previously named `Input Specification` and now we have a list of them within each input item.

**Comment by sei-aderr** [comment]
@sebastian-echeverria

Grace had a couple more changes she wanted to make to the schema that she missed on the first pass. Here is her proposed new structure. I will start working on adjusting the frontend if you could make the changes to the backend.

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Model Information",
    "description": "Schema for the Model Information section of the Negotiation Card",
    "type": "object",
    "properties": {
        "development_compute_resources": {
            "description": "Describe the amount and type of compute resources needed for training",
            "type": "object",
            "properties": {
                "gpu": {
                    "description": "Number of GPUs required for model training",
                    "type": "integer"
                },
                "cpu": {
                    "description": "Number of CPUs required for model training",
                    "type": "integer"
                },
                "memory": {
                    "description": "Amount of memory required for model training (in GB)",
                    "type": "number"
                },
                "storage": {
                    "description": "Amount of storage required for model training (in GB)",
                    "type": "number"
                }
            }
        },
        "deployment_platform": {
            "description": "Describe the platform on which the trained model will be deployed (e.g., local server, cloud server, embedded platform)",
            "type": "string"
        },
        "capability_deployment_mechanism": {
            "description": "Describe how the model capabilities will be made available (e.g., API, user-facing, data feed)",
            "type": "string"
        },
        "input_specification": {
            "description": "Describe the input data types and formats needed for model to conduct inference",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input_name": {
                        "description": "Input name",
                        "type": "string"
                    },
                    "description": {
                        "description": "Short input description",
                        "type": "string"
                    },
                    "type": {
                        "description": "Input type, e.g., number, string, boolean, data, image, audio",
                        "type": "string"
                    },
                    "expected_values": {
                        "description": "Expected values for the input",
                        "type": "string"
                    }
                }
            }
        },
        "output_specification": {
            "description": "Describe the output format and specification needed for the system to ingest model results",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "output_name": {
                        "description": "Output name",
                        "type": "string"
                    },
                    "description": {
                        "description": "Short output description",
                        "type": "string"
                    },
                    "type": {
                        "description": "Output type, e.g., number, string, boolean, data, image, audio",
                        "type": "string"
                    },
                    "expected_values": {
                        "description": "Expected values for the output",
                        "type": "string"
                    }
                }
            }
        },
        "production_compute_resources": {
            "description": "Describe the amount and type of compute resources needed for model inference",
            "type": "object",
            "properties": {
                "gpu": {
                    "description": "Number of GPUs required for model inference",
                    "type": "integer"
                },
                "cpu": {
                    "description": "Number of CPUs required for model inference",
                    "type": "integer"
                },
                "memory": {
                    "description": "Amount of memory required for model inference (in GB)",
                    "type": "number"
                },
                "storage": {
                    "description": "Amount of storage required for model inference (in GB)",
                    "type": "number"
                }
            }
        }
    }
}
```

**Comment by sei-aderr** [comment]
@GALewis 

In the update to the schema, are the `input_specification` and `output_specification` intentionally no longer nested within `interface` like in the previous version?

Then I am also seeing a change where there is no longer `model.development` and `model.production` but instead just specifying the two resource items with `development_compute_resources` and `production_compute_resources` and the change to input/output specification with it being a list with no top level items, and the changes from `name` to `input_name` and `output_name`. 

Are these all the changes that were made?

**Comment by GALewis** [comment]
I believe so.

**Comment by GALewis** [comment]
AH! Yes, true. TEC is much more concrete about these things. I don't want to complicate the Negotiation Card, so can we add each part of each component as an input, prefixed by the component name. For example, if I have two components A and B. A has two inputs a1 and a2. B has two inputs B1 and b2. I would create four inputs (names) A.a1, A.a2, B.b1, and B.b2. Does that make sense?

**Comment by sei-aderr** [comment]
Yes, that makes sense for the import. So stick to the schema that you sent and follow that implementation for the descriptor import?

**Comment by GALewis** [comment]
Yes

**Comment by sei-aderr** [comment]
Frontend updates to match new schema are uploaded. 

@sebastian-echeverria Let me know when the backend is updated and I will test.

**Comment by sei-aderr** [comment]
Grace, how would you like to adjust the report fields for input and output description based on these changes? They were each just a single text field before

**Comment by GALewis** [comment]
I tried to open a report for the IrisClassifier, but I don't think that one has been created. In any case, now that it is in an array, the easiest would be to have a table with the values.

**Comment by GALewis** [comment]
Everything works, except for the Input field from the Development Environment descriptor. It is not populating.

**Comment by sei-aderr** [comment]
Are you wanting the descriptor `upstream_components` to map to negotiation card `model.input_specification`?

Descriptor `downstream_components` maps to negotiation card `model.output_specification` but I thought it was previously an intentional choice to not have the upstream not map to input_specificaiton

**Comment by GALewis** [comment]
Yes, that is where the input should come from. Thanks.

**Comment by sei-aderr** [comment]
Updated `Delete label` to `Delete Label` and the import for `input_specification`

**Comment by sei-aderr** [comment]
Addresses #403, #453,  #454, #458, #459

**Comment by sei-aderr** [comment]
Please approve the PR if everything is good so I can merge @GALewis

**Review by GALewis — APPROVED** [review]
Looks great.

**Pull request merged**
