### PR TITLE
Feature/report UI inputs

### PR DESCRIPTION
**Pull request by sei-aderr**
Addresses #339, #284

### CODE REVIEW

**Comment by sei-aderr** [comment]
Okay, everything should be implemented now and is ready for review.

**Comment by sei-aderr** [comment]
Should be all good to go now @krmaffey 

The navigation bug seems to be a vue bug that is being tracked on the nuxt side here: https://github.com/nuxt/nuxt/issues/13309

The fix that worked for me was just downgrading the version of vue. So to get that version updated in your environment you can navigate to the `mlte/frontend/nuxt-app` directory and then just run

```bash
rm -Rf .nuxt node_modules
npm install
``

Then once those finish `npm run dev` to run the frontend again and it should navigate correctly and not show any console errors.

**Review by krmaffey — DISMISSED** [review]
Looks great, thanks Alex!

**Review by krmaffey — APPROVED** [review]
LGTM!

**Pull request merged**
